### ISSUE TITLE
Přihlašovací/Registrační okno - Trochu bych zmenšil main, zdá se mi to moc roztáhlé

### ISSUE THREAD

**Issue by Bagrborn** [krustowski/littr#7]
Trochu bych zmenšil  main.responsive - max-inline-size na 30rem
Před:
![2](https://github.com/krustowski/litter-go/assets/148314428/db42d9c4-e924-4ac0-bbc8-d126a15256bd)
Po:
![1](https://github.com/krustowski/litter-go/assets/148314428/aa28dbd2-03e9-4289-a415-8f65b6a29b32)

**Comment by Bagrborn** [comment]
+ buttony bych možná menšit ještě víc, třeba klidně i o polovinu.

**Comment by krustowski** [comment]
to by možná šlo vyřešit, @Tackx, is it some CSS switch based on device pls?

**Comment by Tackx** [comment]
@krustowski media queries: https://www.w3schools.com/css/css_rwd_mediaqueries.asp
